//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerDIY
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Jack : DbContext
    {
        public Jack()
            : base("name=Jack")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<P_Promotion> P_Promotion { get; set; }
        public virtual DbSet<P_Account> P_Account { get; set; }
        public virtual DbSet<P_Employee> P_Employee { get; set; }
        public virtual DbSet<P_Customer> P_Customer { get; set; }
        public virtual DbSet<P_Order> P_Order { get; set; }
        public virtual DbSet<P_OrderItem> P_OrderItem { get; set; }
        public virtual DbSet<P_Product> P_Product { get; set; }
    }
}
