//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerDIY
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_OrderItem
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public decimal Price { get; set; }
        public int Amount { get; set; }
        public string Type { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual P_Order P_Order { get; set; }
        public virtual P_Product P_Product { get; set; }
    }
}
